version: '3.7'

services:
  bot:
    build: .
    working_dir: /apps
    container_name: aiogram_bot
    env_file:
      - .env
    command: python main.py
    depends_on:
      - pg
  pg:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=77
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pg_data: